import type { Metadata } from "next";
import { Sen } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Wrapper from "./wrapper";
import { ThemeProvider } from "@/components/theme/ThemeProvider";

const sen = Sen({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={sen.className}>
        <ThemeProvider defaultTheme="system" enableSystem attribute="class">
          <Wrapper>
            <Header />
            {children}
            <Footer />
          </Wrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
